# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Full_Script.py
# Created on: 2016-08-23 08:05:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Full_Script <AllCORS_Select> <Projected_Coverage> <AGO_CORS__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
AllCORS_Select = arcpy.GetParameterAsText(0)
if AllCORS_Select == '#' or not AllCORS_Select:
    AllCORS_Select = "%scratchworkspace%\\AllCORS_Select" # provide a default value if unspecified

Projected_Coverage = arcpy.GetParameterAsText(1)
if Projected_Coverage == '#' or not Projected_Coverage:
    Projected_Coverage = "Projected_Coverage" # provide a default value if unspecified

AGO_CORS__2_ = arcpy.GetParameterAsText(2)
if AGO_CORS__2_ == '#' or not AGO_CORS__2_:
    AGO_CORS__2_ = "C:\\Workspace\\GeodeticInteractive\\AGO_CORS" # provide a default value if unspecified

# Local variables:
AllCORS = "C:\\Workspace\\GeodeticControlGP.gdb\\CORS_sites_Project\\AllCORS"
Expression = "Status = 'Operational' AND (ST = 'AK' OR ST = 'BC')"
Distance__value_or_field_ = "250 Kilometers"
AllCORS_Select_Buffer = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer"
in_memory = "in_memory"
empty = "in_memory\\empty"
Spaghetti = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur"
Output_Feature_Class = Spaghetti
oidfield = Spaghetti
Meatballs = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur1"
All_CORS2_Buffer__2_ = "C:\\Workspace\\GeodeticControlGP.gdb\\CORS_sites_Project\\All_CORS2_Buffer"
count_overlaps = "%scratchworkspace%\\All_CORS2_Buffer_FeatureToPo2"
Threatened_coverage_poor = Output_Feature_Class
Secure_coverage = Output_Feature_Class
Features_to_Delete = "features_to_delete"
Features_Deleted = Features_to_Delete
Delete_succeeded = "true"
v_scratchworkspace___4_ = "%scratchworkspace%"
Threatened_coverage_poor__4_ = Threatened_coverage_poor
Threatened_coverage_poor__2_ = Threatened_coverage_poor__4_
Threatened_coverage_poor_Dis__3_ = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dis"
v_scratchworkspace___2_ = "%scratchworkspace%"
Secure_coverage_shp__2_ = Secure_coverage
Secure_coverage__2_ = Secure_coverage_shp__2_
Secure_coverage_Dissolve = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Secure_coverage_Dissolve"
Threatened_coverage_poor_Dis1 = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dis1"
Threatened_coverage_poor_Dis2 = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dis2"
Alaska_Coast_Simplified_py__2_ = "C:\\Workspace\\GeodeticControlGP.gdb\\Alaska_Coast_Simplified_py"
Threatened_coverage_poor_Dis3__2_ = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dis3"
Coverage_Merge_Union__3_ = Threatened_coverage_poor_Dis3__2_
Threatened_coverage_poor_Dis3 = Coverage_Merge_Union__3_
Alaska_Coast_Simplified_py = "C:\\Workspace\\GeodeticControlGP.gdb\\Alaska_Coast_Simplified_py"
Threatened_coverage_poor_Dis4 = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dis4"
Threatened_coverage_poor_Dizz = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dizz"
v_scratchworkspace_ = "%scratchworkspace%"
Threatened_coverage_poor_Dis = "Threatened_coverage_poor_Dis"
GeodeticInteractive = "C:\\Workspace\\GeodeticInteractive"
AGO_CORS = GeodeticInteractive

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb"

# Process: Select (2)
arcpy.Select_analysis(AllCORS, AllCORS_Select, Expression)

# Process: Buffer (2)
arcpy.Buffer_analysis(AllCORS_Select, AllCORS_Select_Buffer, Distance__value_or_field_, "FULL", "ROUND", "NONE", "", "GEODESIC")

# Process: Create Feature Class
arcpy.CreateFeatureclass_management(in_memory, "empty", "POINT", "", "DISABLED", "DISABLED", "", "", "0", "0", "0")

# Process: Feature To Polygon
tempEnvironment0 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Same As Input"
arcpy.FeatureToPolygon_management("C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer", Spaghetti, "", "NO_ATTRIBUTES", empty)
arcpy.env.outputMFlag = tempEnvironment0

# Process: Calculate Value
arcpy.CalculateValue_management("GetOidFieldName(r\"%Spaghetti%\")", "import arcpy\\ndef GetOidFieldName(path):\\n  fc = arcpy.Describe(path)\\n  return fc.oidfieldname\\n\\n  ", "Field")

# Process: Feature To Point
arcpy.FeatureToPoint_management(Spaghetti, Meatballs, "INSIDE")

# Process: Spatial Join
arcpy.SpatialJoin_analysis(Meatballs, All_CORS2_Buffer__2_, count_overlaps, "JOIN_ONE_TO_ONE", "KEEP_ALL", "", "WITHIN", "", "")

# Process: Join Field
arcpy.JoinField_management(Spaghetti, oidfield, count_overlaps, "ORIG_FID", "Join_Count")

# Process: Make Feature Layer (2)
arcpy.MakeFeatureLayer_management(Output_Feature_Class, Features_to_Delete, "Join_Count = 0", "", "FID_empty FID_empty VISIBLE NONE;Shape_length Shape_length VISIBLE NONE;Shape_area Shape_area VISIBLE NONE;Join_Count Join_Count VISIBLE NONE")

# Process: Delete Features
arcpy.DeleteFeatures_management(Features_to_Delete)

# Process: Delete
arcpy.Delete_management(Features_to_Delete, "")

# Process: Feature Class to Feature Class (4)
arcpy.FeatureClassToFeatureClass_conversion(Output_Feature_Class, v_scratchworkspace___4_, "Threatened_coverage_poor", "Join_Count <3", "FID_empty \"FID_empty\" true true false 0 Long 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur,FID_empty,-1,-1;Shape_length \"Shape_length\" true true false 0 Double 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur,Shape_length,-1,-1;Shape_area \"Shape_area\" true true false 0 Double 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur,Shape_area,-1,-1;Join_Count \"Join_Count\" true true false 0 Long 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur,Join_Count,-1,-1", "")

# Process: Add Field (6)
arcpy.AddField_management(Threatened_coverage_poor, "Coverage", "TEXT", "", "", "20", "Coverage", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (5)
arcpy.CalculateField_management(Threatened_coverage_poor__4_, "Coverage", "\"Inadequate Coverage\"", "PYTHON_9.3", "")

# Process: Dissolve (4)
arcpy.Dissolve_management(Threatened_coverage_poor__2_, Threatened_coverage_poor_Dis__3_, "Coverage", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(Output_Feature_Class, v_scratchworkspace___2_, "Secure_coverage", "Join_Count >2", "FID_empty \"FID_empty\" true true false 0 Long 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur,FID_empty,-1,-1;Shape_length \"Shape_length\" true true false 0 Double 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur,Shape_length,-1,-1;Shape_area \"Shape_area\" true true false 0 Double 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur,Shape_area,-1,-1;Join_Count \"Join_Count\" true true false 0 Long 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\AllCORS_Select_Buffer_Featur,Join_Count,-1,-1", "")

# Process: Add Field (3)
arcpy.AddField_management(Secure_coverage, "Coverage", "TEXT", "", "", "20", "Coverage", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (6)
arcpy.CalculateField_management(Secure_coverage_shp__2_, "Coverage", "\"Adequate Coverage\"", "PYTHON_9.3", "")

# Process: Dissolve
arcpy.Dissolve_management(Secure_coverage__2_, Secure_coverage_Dissolve, "Coverage", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Erase
arcpy.Erase_analysis(Threatened_coverage_poor_Dis__3_, Secure_coverage_Dissolve, Threatened_coverage_poor_Dis1, "")

# Process: Merge
arcpy.Merge_management("C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dis1;C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Secure_coverage_Dissolve", Threatened_coverage_poor_Dis2, "Coverage \"Coverage\" true true false 20 Text 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\GeodeticControl.gdb\\Adequate_coverage,Coverage,-1,-1,C:\\Workspace\\GeodeticInteractive\\GeodeticControl.gdb\\Adequate_coverage,Coverage,-1,-1,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dis1,Coverage,-1,-1,C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Secure_coverage_Dissolve,Coverage,-1,-1;Shape_length \"Shape_length\" true true false 0 Double 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\GeodeticControl.gdb\\Adequate_coverage,Shape_Length,-1,-1,C:\\Workspace\\GeodeticInteractive\\GeodeticControl.gdb\\Adequate_coverage,Shape_length,-1,-1;Shape_area \"Shape_area\" true true false 0 Double 0 0 ,First,#,C:\\Workspace\\GeodeticInteractive\\GeodeticControl.gdb\\Adequate_coverage,Shape_Area,-1,-1,C:\\Workspace\\GeodeticInteractive\\GeodeticControl.gdb\\Adequate_coverage,Shape_area,-1,-1")

# Process: Union
arcpy.Union_analysis("C:\\Workspace\\GeodeticInteractive\\Scratch\\Scratch.gdb\\Threatened_coverage_poor_Dis2 #;C:\\Workspace\\GeodeticControlGP.gdb\\Alaska_Coast_Simplified_py #", Threatened_coverage_poor_Dis3__2_, "NO_FID", "", "GAPS")

# Process: Delete Field
arcpy.DeleteField_management(Threatened_coverage_poor_Dis3__2_, "FEATURE;RFRSHDT")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Coverage_Merge_Union__3_, "Coverage", "output( !Coverage! )", "PYTHON_9.3", "def output(Coverage):\\n    if (Coverage == \"\"):\\n        Coverage = \"No Coverage\"\\n        return Coverage\\n    else:\\n        return Coverage")

# Process: Clip
arcpy.Clip_analysis(Threatened_coverage_poor_Dis3, Alaska_Coast_Simplified_py, Threatened_coverage_poor_Dis4, "")

# Process: Dissolve (3)
arcpy.Dissolve_management(Threatened_coverage_poor_Dis4, Threatened_coverage_poor_Dizz, "Coverage", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Threatened_coverage_poor_Dizz, Threatened_coverage_poor_Dis, "", v_scratchworkspace_, "Coverage Coverage VISIBLE NONE")

# Process: Create Folder
arcpy.CreateFolder_management(GeodeticInteractive, "AGO_CORS")

# Process: Feature Class To Shapefile (multiple)
tempEnvironment0 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "C:\\Workspace\\GeodeticInteractive\\Scratch"
arcpy.FeatureClassToShapefile_conversion("%scratchworkspace%\\AllCORS_Select;Threatened_coverage_poor_Dis", AGO_CORS)
arcpy.env.scratchWorkspace = tempEnvironment0

# Process: Make Feature Layer (3)
arcpy.MakeFeatureLayer_management(Threatened_coverage_poor_Dis, Projected_Coverage, "", AGO_CORS__2_, "Coverage Coverage VISIBLE NONE")

